version: "3.3"
volumes:
  htdocs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.142.0.2
      device: ":/var/nfs/general"
services:
  web:
    image: tutum/apache-php
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - type: volume
        source: htdocs
        target: /app
    ports:
      - "80:80"
   
  mysql:
    image: mariadb
    volumes:
       - type: bind
         source: ./mysql
         target: /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: penjualan
    ports:
       - "8889:3306"